version: '3.8'

services:
  app:
    build: .
    # Constrói a imagem a partir do Dockerfile no diretório atual (.)
    container_name: api 
    # Mapeia a porta 8000 do seu computador (host) para a porta 8000 do contêiner
    ports:
      - "8000:8000"
    # Monta o diretório atual (.) no diretório /app do contêiner.
    # Isso permite que as alterações no código sejam refletidas instantaneamente
    # no contêiner (hot-reloading) e que o banco de dados SQLite (escola.db)
    # seja salvo na sua máquina local.
    volumes:
      - .:/app
    # Comando para iniciar a aplicação com uvicorn.
    # --host 0.0.0.0 é necessário para que a API seja acessível de fora do contêiner.
    # --reload ativa o recarregamento automático ao detectar mudanças no código.
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload